task: detection

num_classes: 2
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/nery/desafio_agscan/ds_terrestres
    ann_file: /home/nery/desafio_agscan/runs/labelme2coco/dataset.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 4
  num_workers: 1
  drop_last: False 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/nery/desafio_agscan/ds_terrestres
    ann_file: /home/nery/desafio_agscan/runs/labelme2coco/dataset.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 1
  num_workers: 1
  drop_last: False
